#!/bin/bash

git submodule add https://github.com/vim-scripts/YankRing.vim bundle/yankring.vim
git add .
git commit -m "Install YankRing.vim bundle as a submodule."

git submodule add https://github.com/vim-scripts/Gundo bundle/gundo
git add .
git commit -m "Install Gundo bundle as a submodule."

git submodule add https://github.com/vim-scripts/matchit.zip  bundle/matchit
git add .
git commit -m "Install matchit.zip bundle as a submodule."

git submodule add https://github.com/mtth/scratch.vim bundle/scratch.vim
git add .
git commit -m "Install scratch.vim bundle as a submodule."

git submodule add https://github.com/tpope/gem-shut-the-fuck-up bundle/gem-shut-the-fudge-up
git add .
git commit -m "Install gem-shut-the-fuck-up bundle as a submodule."

