#!/bin/bash

git submodule add --force https://github.com/vim-scripts/Gundo bundle/gundo
git add .
git commit -m "Install Gundo bundle as a submodule."

git submodule add --force https://github.com/vim-scripts/matchit.zip  bundle/matchit
git add .
git commit -m "Install matchit.zip bundle as a submodule."

git submodule add --force https://github.com/mtth/scratch.vim bundle/scratch.vim
git add .
git commit -m "Install scratch.vim bundle as a submodule."

